package com.smartdroneinspection.maintenance.domain.enums;

public enum MaintenanceTicketStatus {
  SUBMITTED,
  ASSESSMENT_PENDING,
  ASSESSED,
  QUOTATION_PENDING,
  AWAITING_CLIENT_APPROVAL,
  ORDER_CONFIRMED,
  EXECUTION_PENDING,
  IN_PROGRESS,
  CHANGE_PENDING,
  INTERNAL_REVIEW,
  RELEASED,
  REWORK_REQUESTED,
  REINSPECTION_REQUESTED,
  CLOSED,
  CANCELLED
}
