<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);NETSDK1023</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\SmartDroneInspection.Domain\SmartDroneInspection.Domain.csproj" />
    <ProjectReference Include="..\..\src\SmartDroneInspection.Application\SmartDroneInspection.Application.csproj" />
    <ProjectReference Include="..\..\src\SmartDroneInspection.Infrastructure\SmartDroneInspection.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\SmartDroneInspection.Api\SmartDroneInspection.Api.csproj" />
  </ItemGroup>

</Project>
